### ISSUE TITLE
How to iterate through all users

### ISSUE THREAD

**Issue by Ermilin** [aboudicheng/mern-graphql-jwt#1]
Hi, great guide.
How would I go about iterating through all registered users in an `<ul>` located in Home/auth.js?

**Comment by aboudicheng** [comment]
Hi. You'll have to write a separate handler inside `resolvers/handlerGenerators/auth.js` that iterates through your registered users from your database.

An example way of doing so would be something like this:
```
// resolvers/handlerGenerators/auth.js
export async function getAllUsers() {
  try {
    const users = await User.find({});
    return users;
  }
  catch (err) {
    throw err
  }
}
```
And in your graphql schema:
```
type RootQuery {
  getAllUsers(): [Users]
}
```

In `Home/auth.js` simply fetch the result inside `useEffect()` query the data:
```
query {
  getAllUsers() {
    users {
      // get necessary data
    }
  }
}
```

Update the results to your state variable and simply use `.map()` method to iterate them as you would for any kind of list items.

Currently not able to test it out, so cannot guarantee if everything is going to work properly here. Let me know if you have any problems later on.
