### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by larrywal** [aboudicheng/mern-graphql-jwt#3]
1) Am trying to get this project working....in VS Code I have debugger for chrome installed, but I can't get breakpoints or other connections to work.  I also don't see sourcemaps in the browser when I navigate to localhost:3000 directly.  Can you give guidance?

2) In client\src\components\app\withauthenticate\index.js  why do you need to call 

            const user = await data.data.verifyToken;

on line 23?  Given the query is being made async on line 22, shouldn't the response already be coming back with the completed query results?

**Comment by aboudicheng** [comment]
Sorry that I took so long to see this, I don't know why I didn't receive any notification from this :(

Not sure if you have already solved the problem yet:
1. Have you successfully ran a standalone `create-react-app` project before? If it works, then it most probably should work exactly the same here. Also check if there is any other warning or error message after running `yarn start` or `npm start`

2. You are correct, that is actually unnecessary! I would really appreciate if you could send a PR to fix this. Thanks for catching it!
